import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Navbar } from "../components/Layout/Navbar";
import { Sidebar } from "../components/Layout/Sidebar";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

type layoutRootProps = {
	readonly children: React.ReactNode;
};

export default function RootLayout({ children }: layoutRootProps) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<div className="flex flex-col h-dvh">
					<Navbar />

					<div className="flex flex-1 overflow-hidden">
						<Sidebar />
						<main className="flex-1 overflow-auto p-4"> {children}</main>
					</div>
				</div>
			</body>
		</html>
	);
}
